"""add column keyword to scrapping_request table

Revision ID: 65ff44dcea1e
Revises: c9000a8f73a3
Create Date: 2025-09-28 20:42:44.777028

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "65ff44dcea1e"
down_revision: Union[str, Sequence[str], None] = "c9000a8f73a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scrapping_requests", sa.Column("keyword", sa.VARCHAR(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scrapping_requests", "keyword")
    # ### end Alembic commands ###
